[workspace]
resolver = "3"
members = ["crates/core", "crates/synth-worklet"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "UNLICENSED"
publish = false
rust-version = "1.98"

[workspace.dependencies]
libm = "0.2.16"
juicyloops-dsp-core = { path = "crates/core" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = false
strip = true
incremental = false
