import { Dest, type PatchModel } from './params';

/**
 * Factory presets of the patch synths. Values are by parameter key without the `patch.` prefix; anything left out
 * is the parameter's default (see `normalizePatch`), so every preset starts from the init patch.
 */
export interface PatchPreset {
    name: string;
    model: PatchModel;
    patch: Record<string, number>;
}

/** LFO sync indexes (`LFO_SYNCS`). */
const SYNC = { bar: 2, half: 3, quarter: 5, eighth: 8, sixteenth: 11 } as const;

const analog: Omit<PatchPreset, 'model'>[] = [
    { name: 'Init', patch: {} },
    {
        name: 'Super saw',
        patch: { unison: 7, detune: 0.35, spread: 1, 'filter.cutoff': 9000, 'amp.attack': 0.01, 'amp.decay': 0.3, 'amp.sustain': 0.85, 'amp.release': 0.5, volume: 0.6 },
    },
    {
        name: 'Fat bass',
        patch: {
            'osc2.wave': 3,
            'osc2.octave': -1,
            'osc2.level': 0.6,
            sub: 0.5,
            'filter.cutoff': 160,
            'filter.resonance': 0.25,
            'filter.env': 0.45,
            'filterEnv.attack': 0.002,
            'filterEnv.decay': 0.25,
            'filterEnv.sustain': 0,
            'filterEnv.release': 0.1,
            'amp.attack': 0.002,
            'amp.decay': 0.3,
            'amp.sustain': 0.8,
            'amp.release': 0.06,
        },
    },
    {
        name: 'Acid',
        patch: {
            'filter.cutoff': 220,
            'filter.resonance': 0.82,
            'filter.env': 0.55,
            'filter.drive': 0.45,
            'filter.velocity': 0.5,
            'filterEnv.decay': 0.2,
            'filterEnv.sustain': 0,
            'filterEnv.release': 0.1,
            'amp.decay': 0.2,
            'amp.sustain': 0.7,
            'amp.release': 0.05,
            glide: 0.06,
        },
    },
    {
        name: 'Warm pad',
        patch: {
            'osc2.fine': 8,
            'osc2.level': 0.8,
            'osc3.wave': 1,
            'osc3.octave': 1,
            'osc3.level': 0.3,
            unison: 3,
            detune: 0.25,
            spread: 0.8,
            'filter.type': 2,
            'filter.cutoff': 1400,
            'filter.resonance': 0.15,
            'filter.env': 0.15,
            'filterEnv.attack': 1.2,
            'filterEnv.decay': 2,
            'filterEnv.sustain': 0.6,
            'filterEnv.release': 2,
            'amp.attack': 0.9,
            'amp.decay': 1,
            'amp.sustain': 0.85,
            'amp.release': 2.2,
            'lfo1.shape': 1,
            'lfo1.rate': 0.25,
            'lfo1.retrigger': 0,
            'lfo1.dest': Dest.cutoff,
            'lfo1.amount': 0.12,
            'lfo2.rate': 4.5,
            'lfo2.dest': Dest.pitch,
            'lfo2.amount': 0.004,
            'lfo2.fade': 1,
            volume: 0.6,
        },
    },
    {
        name: 'Brass',
        patch: {
            'osc2.fine': -7,
            'osc2.level': 0.9,
            'filter.cutoff': 500,
            'filter.resonance': 0.1,
            'filter.env': 0.45,
            'filterEnv.attack': 0.06,
            'filterEnv.decay': 0.5,
            'filterEnv.sustain': 0.45,
            'filterEnv.release': 0.2,
            'amp.attack': 0.03,
            'amp.decay': 0.2,
            'amp.sustain': 0.9,
            'amp.release': 0.2,
            'lfo1.rate': 5.5,
            'lfo1.dest': Dest.pitch,
            'lfo1.amount': 0.006,
            'lfo1.fade': 0.6,
        },
    },
    {
        name: 'Pluck',
        patch: {
            'osc1.wave': 3,
            'osc1.width': 0.3,
            'osc2.octave': 1,
            'osc2.level': 0.25,
            'filter.type': 2,
            'filter.cutoff': 350,
            'filter.resonance': 0.3,
            'filter.env': 0.65,
            'filter.keyTrack': 0.5,
            'filterEnv.decay': 0.22,
            'filterEnv.sustain': 0,
            'filterEnv.release': 0.2,
            'amp.decay': 0.45,
            'amp.sustain': 0,
            'amp.release': 0.35,
        },
    },
    {
        name: 'Wobble bass',
        patch: {
            'osc2.wave': 3,
            'osc2.octave': -1,
            'osc2.level': 0.7,
            sub: 0.4,
            'filter.cutoff': 180,
            'filter.resonance': 0.55,
            'filter.drive': 0.3,
            'lfo1.sync': SYNC.eighth,
            'lfo1.dest': Dest.cutoff,
            'lfo1.amount': 0.45,
            'amp.release': 0.08,
        },
    },
    {
        name: 'Soft lead',
        patch: {
            'osc1.wave': 3,
            'osc1.width': 0.42,
            'osc2.fine': 5,
            'osc2.level': 0.5,
            'filter.cutoff': 2800,
            'filter.resonance': 0.2,
            'filter.env': 0.2,
            glide: 0.04,
            'lfo1.rate': 5.8,
            'lfo1.dest': Dest.pitch,
            'lfo1.amount': 0.006,
            'lfo1.fade': 0.4,
            'amp.attack': 0.01,
            'amp.sustain': 0.9,
            'amp.release': 0.25,
        },
    },
    {
        name: 'Noise sweep',
        patch: {
            'osc1.level': 0,
            noise: 1,
            'filter.type': 3,
            'filter.cutoff': 400,
            'filter.resonance': 0.7,
            'lfo1.shape': 2,
            'lfo1.rate': 0.25,
            'lfo1.dest': Dest.cutoff,
            'lfo1.amount': 0.5,
            'amp.attack': 0.5,
            'amp.release': 1.5,
            volume: 0.5,
        },
    },
];

const wavetable: Omit<PatchPreset, 'model'>[] = [
    { name: 'Init', patch: {} },
    {
        name: 'Morph pad',
        patch: {
            'osc1.position': 0.2,
            'osc2.table': 2,
            'osc2.position': 0.5,
            'osc2.fine': 7,
            'osc2.level': 0.7,
            unison: 3,
            detune: 0.2,
            spread: 0.9,
            'filter.type': 2,
            'filter.cutoff': 3000,
            'amp.attack': 0.8,
            'amp.decay': 1,
            'amp.sustain': 0.85,
            'amp.release': 2,
            'lfo1.shape': 1,
            'lfo1.rate': 0.15,
            'lfo1.retrigger': 0,
            'lfo1.dest': Dest.shapeA,
            'lfo1.amount': 0.35,
            volume: 0.6,
        },
    },
    {
        name: 'Vox lead',
        patch: {
            'osc1.table': 3,
            'osc1.position': 0.1,
            'filter.cutoff': 6000,
            'lfo1.shape': 1,
            'lfo1.sync': SYNC.bar,
            'lfo1.dest': Dest.shapeA,
            'lfo1.amount': 0.8,
            'lfo2.rate': 5.5,
            'lfo2.dest': Dest.pitch,
            'lfo2.amount': 0.005,
            'lfo2.fade': 0.5,
            glide: 0.05,
            'amp.attack': 0.02,
            'amp.sustain': 0.9,
            'amp.release': 0.3,
        },
    },
    {
        name: 'Growl bass',
        patch: {
            'osc1.table': 7,
            'osc1.position': 0.3,
            'osc1.octave': -1,
            sub: 0.5,
            'filter.cutoff': 900,
            'filter.resonance': 0.3,
            'filter.drive': 0.4,
            'lfo1.sync': SYNC.sixteenth,
            'lfo1.dest': Dest.shapeA,
            'lfo1.amount': 0.6,
            'amp.release': 0.08,
        },
    },
    {
        name: 'Sync sweep',
        patch: {
            'osc1.table': 4,
            'filter.cutoff': 8000,
            'mod1.source': 3,
            'mod1.dest': Dest.shapeA,
            'mod1.amount': 0.9,
            'filterEnv.decay': 0.6,
            'filterEnv.sustain': 0,
            'amp.decay': 0.6,
            'amp.sustain': 0.5,
            'amp.release': 0.3,
        },
    },
    {
        name: 'Glass keys',
        patch: {
            'osc1.table': 6,
            'osc1.position': 0.25,
            'osc2.table': 0,
            'osc2.octave': 1,
            'osc2.level': 0.3,
            'mod1.source': 5,
            'mod1.dest': Dest.shapeA,
            'mod1.amount': 0.4,
            'filter.type': 0,
            'amp.decay': 1.5,
            'amp.sustain': 0.2,
            'amp.release': 0.8,
        },
    },
    {
        name: 'Organ',
        patch: {
            'osc1.table': 2,
            'osc1.position': 0.6,
            'filter.type': 0,
            'amp.attack': 0.005,
            'amp.sustain': 1,
            'amp.release': 0.08,
            'lfo1.rate': 6,
            'lfo1.retrigger': 0,
            'lfo1.dest': Dest.volume,
            'lfo1.amount': 0.08,
        },
    },
];

/** Operator values by number, flattened to `op<n>.<field>` keys. */
const ops = (fields: Record<number, Record<string, number>>): Record<string, number> =>
    Object.fromEntries(Object.entries(fields).flatMap(([n, values]) => Object.entries(values).map(([field, value]) => [`op${n}.${field}`, value])));

const fm: Omit<PatchPreset, 'model'>[] = [
    { name: 'Init', patch: {} },
    {
        name: 'E. piano',
        patch: {
            'fm.algorithm': 4,
            ...ops({
                1: { ratio: 1, level: 1, decay: 1.5, sustain: 0.2, release: 0.5 },
                2: { ratio: 14, level: 0.25, decay: 0.3, sustain: 0, velocity: 0.9 },
                3: { ratio: 1, level: 0.8, decay: 2.5, sustain: 0.15, release: 0.5 },
                4: { ratio: 1, level: 0.45, decay: 0.8, sustain: 0.1, velocity: 0.8 },
            }),
            'amp.attack': 0.002,
            'amp.sustain': 1,
            'amp.release': 0.4,
        },
    },
    {
        name: 'Bell',
        patch: {
            'fm.algorithm': 4,
            ...ops({
                1: { ratio: 1, decay: 4, sustain: 0, release: 3 },
                2: { ratio: 3.5, level: 0.6, decay: 3, sustain: 0, release: 2 },
                3: { ratio: 1, level: 0.6, detune: 4, decay: 3, sustain: 0, release: 3 },
                4: { ratio: 7, level: 0.4, decay: 2, sustain: 0, release: 2 },
            }),
            'amp.sustain': 1,
            'amp.release': 3,
        },
    },
    {
        name: 'FM bass',
        patch: {
            'fm.algorithm': 0,
            'fm.feedback': 0.2,
            ...ops({
                1: { ratio: 1, level: 1, sustain: 1 },
                2: { ratio: 1, level: 0.55, decay: 0.25, sustain: 0.2 },
                3: { ratio: 2, level: 0.3, decay: 0.15, sustain: 0 },
                4: { ratio: 1, level: 0 },
            }),
            'amp.decay': 0.3,
            'amp.sustain': 0.8,
            'amp.release': 0.08,
        },
    },
    {
        name: 'Organ',
        patch: {
            'fm.algorithm': 7,
            ...ops({
                1: { ratio: 0.5, level: 0.8, sustain: 1, velocity: 0 },
                2: { ratio: 1, level: 0.8, sustain: 1, velocity: 0 },
                3: { ratio: 2, level: 0.6, sustain: 1, velocity: 0 },
                4: { ratio: 3, level: 0.4, sustain: 1, velocity: 0 },
            }),
            'amp.sustain': 1,
            'amp.release': 0.08,
        },
    },
    {
        name: 'Metal pluck',
        patch: {
            'fm.algorithm': 1,
            ...ops({
                1: { ratio: 1, decay: 0.8, sustain: 0, release: 0.5 },
                2: { ratio: 1.41, level: 0.7, decay: 0.4, sustain: 0 },
                3: { ratio: 3.3, level: 0.5, decay: 0.3, sustain: 0 },
                4: { ratio: 5.19, level: 0.4, decay: 0.2, sustain: 0 },
            }),
            'amp.decay': 1,
            'amp.sustain': 0,
            'amp.release': 0.5,
        },
    },
    {
        name: 'FM brass',
        patch: {
            'fm.algorithm': 0,
            'fm.feedback': 0.35,
            ...ops({
                1: { ratio: 1, level: 1, attack: 0.03, sustain: 1 },
                2: { ratio: 1, level: 0.6, attack: 0.08, decay: 0.3, sustain: 0.7 },
                3: { ratio: 1, level: 0.2, sustain: 0.5 },
                4: { ratio: 1, level: 0.2 },
            }),
            'amp.attack': 0.03,
            'amp.sustain': 0.9,
            'amp.release': 0.2,
            'lfo1.rate': 5.5,
            'lfo1.dest': Dest.pitch,
            'lfo1.amount': 0.006,
            'lfo1.fade': 0.5,
        },
    },
];

export const PATCH_FACTORY: Record<PatchModel, readonly PatchPreset[]> = {
    analog: analog.map((preset) => ({ ...preset, model: 'analog' })),
    wavetable: wavetable.map((preset) => ({ ...preset, model: 'wavetable' })),
    fm: fm.map((preset) => ({ ...preset, model: 'fm' })),
};
